### ISSUE TITLE
Video not playing, just a white screen

### ISSUE THREAD

**Issue by VogelMoritz** [picoxr/Broadcast#2]
I've connected to headset to the server - it shows up, status get's updated and I can reboot it. 
I've set up the video in the server panel including thumbnail and copies the whole pre_resource folder into the root of the headset. On the headset in video tab under free mode, the thumbnail image shows up.

However, as soon as I start the video in free mode on the headset or kiosk mode from the server, I only see a white screen or all white on the headset, depending on video type. 

From the docs, I see you are using BitVideoPlayer, but the scripts are not included in the client unity project. In the unity project, you are using unity player all along, so it seems the docs are outdated. 

Can you point me to the issue or send my a working example?

Thank you very much!

**Comment by picoxr** [comment]
The player provided by Demo is the Video Player.
The video cannot be played. It may be that the video is not copied or the video format is not supported.
Can you send the Pre_Resource folder to support@picovr.com

**Comment by VogelMoritz** [comment]
Thank you for your response!
I did a reset of the headset and could bring the demo to work this morning. 

Only one video is unexpectedly failing now, but it doesn't matter since it is just a preview clip for testing (maybe H264@High profile is the issue here). 

This thread can be closed.
